document.write("<table width=760 border=0 cellspacing=0 cellpadding=0 height=53 align=center>");
document.write("<tr>");
document.write("  <td width=95 align=right><img src=imgnew/friendlinkleft.gif width=89 height=53></td>");
document.write("  <td width=28 align=right>&nbsp;</td>");
document.write("  <td width=537><a href=http://www.80city.com target=_blank><img src=images/city.gif width=88 height=30 border=0></a> ");
document.write("  <a href=http://www.tickets365.com.cn target=_blank><img src=images/tickets365_logo_88x31.gif width=88 height=31 border=0></a> ");
document.write("  </td>    ");
document.write("  <td width=100 align=center><img src=imgnew/friendlinkrightt.gif width=69 height=53></td>");
document.write("  </tr>");
document.write("  </table>");
